language: python
python: "3.7"
services:
  - postgresql
  - docker
addons:
  postgresql: '11'
env:
  global:
    - DBHOST=localhost
    - PGUSER=postgres
    - PGPASS=
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11 
#
  - docker build -t foobar .
  - docker run -d -p 127.0.0.1:80:4567 foobar /bin/sh -c "cd C:\Program Files\Docker; bundle exec foreman start;"
  - docker ps -a
  - docker run foobar /bin/sh -c "cd C:\Program Files\Docker; bundle exec rake test"

install:
  - pip install -r requirements.txt

#before_script:
#  - psql -c 'create database todo;' -U postgres
#  - mv mysite/settings.py.travis mysite/settings.py

before_script: cd "YEET/"

script: 
  - python manage.py test
  - bundle exec rake test
#  - chmod +x run_sonar.sh && ./run_sonar.sh

